### ISSUE TITLE
Deepfry

### ISSUE THREAD

**Issue by itz63c** [KenHV/KensurBot#19]
Could you change deepfrying to rely on this? I feel that it provides a better deepfry

https://github.com/Ovyerus/deeppyer

There's code for it in here that you might be able to use. https://github.com/skittles9823/skitt_bot/blob/master/skitt_bot/modules/memes.py

**Comment by KenHV** [comment]
I'll consider it when I find time to work on the bot

**Comment by KenHV** [comment]
I tried this out but the current implementation looks better IMHO :D

**Comment by itz63c** [comment]
oof
